dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
<<<<<<< HEAD
  - "3.9"
=======
>>>>>>> 57474f213cf7d04850d8115ff0b31d98483fa138
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest
